/*
 * EditorTextualMundo.java
 *
 * Created on 22 de Abril de 2008, 23:02
 */

package tangram.gui;

import gals.AnalysisError;
import gals.Compiler;

import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;

import javax.swing.text.Element;

import tangram.Figura;
import tangram.Mundo;
import tangram.comandos.ModeloExecutavel;
import tangram.comandos.MundoExecutavel;
import tangram.io.ReadWriteFile;

/**
 *
 * @author  GlauKo
 */
public class EditorTextualMundo extends javax.swing.JFrame {
    
    /** Creates new form EditorTextualMundo */
    public EditorTextualMundo(Mundo mundo) {
        this.mundo = mundo;
        initComponents();
        jcbAcoes.removeAllItems();
    }
    
    public void insereComando(String comando){
        String text = jtaCodigo.getText();
        String newText;
        int posicaoFinal = lineEndOffset - 1;
        
        if(lineEndOffset == 0)
            newText = comando + text;
        else
            newText = text.substring(0, lineEndOffset - 1) + 
                    (lineEndOffset-1 != lineStartOffset ? "\n" : "") +
                    comando + text.substring(lineEndOffset - 1);
        jtaCodigo.setText(newText);
        jtaCodigo.requestFocus();
        try{
            jtaCodigo.setCaretPosition(posicaoFinal + 1);
            mundo.getEditorGrafico().requestFocus();
        } catch (Exception e){}
    }
    
    private void preExecuta(){
        MundoExecutavel exe = mundo.Compila();
        if (exe == null)
            return;
        
        //
        exe.start();
    }
    
    public void setSelectedModel(String modelName,
            ArrayList<String>modelAction, File file, Figura figura){
        jcbAcoes.removeAllItems();
        if(modelName != null){
            lbModelName.setText(modelName);
            for (String s : modelAction ){
                jcbAcoes.addItem(s);
            }
            this.file = file;
            this.figura = figura;
        } else
            lbModelName.setText("Nenhum Modelo Selecionado");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        jtaCodigo = new javax.swing.JTextArea();
        jbLinha = new javax.swing.JLabel();
        jbHelp = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbtPlay = new javax.swing.JButton();
        lbModelName = new javax.swing.JLabel();
        jcbAcoes = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setTitle("Editor Textual de Mundos - " + mundo.getNomeDoMundo());
        setIconImage(Toolkit.getDefaultToolkit().createImage(getClass().getResource("/Imagens/Tangram.png")));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jtaCodigo.setColumns(20);
        jtaCodigo.setRows(5);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${mundo.codigo}"), jtaCodigo, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jtaCodigo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtaCodigoCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(jtaCodigo);

        jbLinha.setText("jbLinha");

        jbHelp.setText("rodapé");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jbtPlay.setText(">");
        jbtPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPlayActionPerformed(evt);
            }
        });

        lbModelName.setText("Nenhum Modelo Selecionado");

        jcbAcoes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("faça");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionaComandoFaca(evt);
            }
        });

        jButton2.setText("faça em paralelo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("VIVA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Animar!");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jbtPlay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbModelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jcbAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbModelName)
                    .addComponent(jcbAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jbtPlay)
                    .addComponent(jButton4)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbLinha)
                        .addGap(18, 18, 18)
                        .addComponent(jbHelp, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLinha)
                    .addComponent(jbHelp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbLinha.setText("");
        jbHelp.setText("");

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtaCodigoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtaCodigoCaretUpdate
        Element root = jtaCodigo.getDocument().getDefaultRootElement();
        dot = evt.getDot();
        line = root.getElementIndex( dot );
        lineStartOffset = root.getElement( line ).getStartOffset();
        lineEndOffset = root.getElement( line ).getEndOffset();
        col = dot - lineStartOffset;
        
        jbLinha.setText((line+1) + ":" + (col+1));
    }//GEN-LAST:event_jtaCodigoCaretUpdate

    private void jbtPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPlayActionPerformed
        try{
            Compiler compiler = new Compiler(ReadWriteFile.read(file));
            final ModeloExecutavel me = compiler.compileModel();
            me.setFigura(figura);
            new Thread(){
                @Override
                public void run(){
                    me.execute((String)jcbAcoes.getSelectedItem());
                }
            }.start();
        } catch (AnalysisError ex){
            Msg.aviso(ex.getMessage());
        }
}//GEN-LAST:event_jbtPlayActionPerformed

    private void AdicionaComandoFaca(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionaComandoFaca
        String comando = (String) jcbAcoes.getSelectedItem();
        if(comando != null && comando.length() > 0)
            insereComando("faça " + lbModelName.getText() + "." + comando);
    }//GEN-LAST:event_AdicionaComandoFaca

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        mundo.fechar();
}//GEN-LAST:event_formWindowClosing

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String comando = (String) jcbAcoes.getSelectedItem();
    if(comando != null && comando.length() > 0)
        insereComando("faça " + lbModelName.getText() +
                "." + comando + " em paralelo");
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String comando = (String) jcbAcoes.getSelectedItem();
    if(comando != null && comando.length() > 0)
        insereComando("faça " + lbModelName.getText() +
                ".VIVA(" + comando + ")");
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    preExecuta();
}//GEN-LAST:event_jButton4ActionPerformed
    
    // Variaveis para contrelo de linhas do editor de texto
    int dot,line,col,lineStartOffset,lineEndOffset;
    
    File file;
    Figura figura;
    
    private Mundo mundo;

    public void setMundo(Mundo mundo) {
        this.mundo = mundo;
    }

    public Mundo getMundo() {
        return mundo;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jbHelp;
    private javax.swing.JLabel jbLinha;
    private javax.swing.JButton jbtPlay;
    private javax.swing.JComboBox jcbAcoes;
    private javax.swing.JTextArea jtaCodigo;
    private javax.swing.JLabel lbModelName;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    
}
