/*
 * InsereComandoEspelha.java
 *
 * Created on 6 de Julho de 2008, 19:28
 */

package tangram.gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;

import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * 
 * @author GlauKo
 */
public class InsereComandoEspelha extends javax.swing.JPanel {

	boolean gerarCodigo;
	JDialog dialog;

	/** Creates new form InsereComandoEspelha */
	public InsereComandoEspelha(ArrayList metodos) {
		initComponents();
		gerarCodigo = false;
		painelSelecionaPeca1.setListaParaSelecao(metodos);
	}

	public String showDialog(JFrame frame) {
		String codigo = null;
		if (dialog == null) {
			// cria um novo dialog
			dialog = new JDialog(frame, "Insere Comando Espelha", true);
			// adiciona este painel no dialog
			dialog.add(this);
			dialog.pack();
			Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
			dialog.setLocation((tela.width - dialog.getSize().width) / 2, (tela.height - dialog.getSize().height) / 2);
		}
		// mostra o dialog e segura a execução até o fechamento do mesmo
		dialog.setVisible(true);
		// se confirmou
		if (gerarCodigo) {
			// cria nova string
			codigo = new String();
			codigo += painelSelecionaPeca1.getSelected() + ".espelha";
		}
		return codigo;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		painelSelecionaPeca1 = new PainelSelecionaPeca();
		jbtConfirma = new javax.swing.JButton();
		jbtCancela = new javax.swing.JButton();

		jbtConfirma.setText("Confirmar");
		jbtConfirma.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbtConfirmaconfirma(evt);
			}
		});

		jbtCancela.setText("Cancelar");
		jbtCancela.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbtCancelacancelar(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(painelSelecionaPeca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGroup(
								layout.createSequentialGroup().addComponent(jbtConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE).addGap(162, 162, 162).addComponent(jbtCancela, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent(painelSelecionaPeca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jbtConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jbtCancela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addContainerGap()));
	}// </editor-fold>//GEN-END:initComponents

	private void jbtConfirmaconfirma(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbtConfirmaconfirma
	// Valida os Campos
		if (validaEntrada()) {
			// se valiu retorna
			gerarCodigo = true;
			dialog.setVisible(false);
		}
	}// GEN-LAST:event_jbtConfirmaconfirma

	private void jbtCancelacancelar(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbtCancelacancelar
		dialog.setVisible(false);
	}// GEN-LAST:event_jbtCancelacancelar

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jbtCancela;
	private javax.swing.JButton jbtConfirma;
	private PainelSelecionaPeca painelSelecionaPeca1;

	// End of variables declaration//GEN-END:variables

	private boolean validaEntrada() {
		if (painelSelecionaPeca1.getSelected() == null) {
			Msg.erro("Entrada inválida!");
			painelSelecionaPeca1.requestFocus();
			return false;
		}
		return true;
	}
}
