/*
 * InsereComandoCor.java
 *
 * Created on 6 de Julho de 2008, 19:31
 */

package tangram.gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;

import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author  GlauKo
 */
public class InsereComandoCor extends javax.swing.JPanel {

    String cor;
    boolean gerarCodigo;
    JDialog dialog;
    
    /** Creates new form InsereComandoCor */
    public InsereComandoCor(ArrayList metodos) {
        initComponents();
        gerarCodigo = false;
        painelSelecionaPeca1.setListaParaSelecao(metodos);
        cor = null;
    }
    
    public String showDialog(JFrame frame){
        String codigo = null;
        if( dialog == null){
            // cria um novo dialog
            dialog = new JDialog(frame, "Insere Comando Cor", true);
            // adiciona este painel no dialog
            dialog.add(this);
            dialog.pack();
            Dimension tela =  Toolkit.getDefaultToolkit().getScreenSize();  
            dialog.setLocation( (tela.width - dialog.getSize().width)/2, 
                    (tela.height - dialog.getSize().height)/2 );
        }
        // mostra o dialog e segura a execução até o fechamento do mesmo
        dialog.setVisible(true);
        // se confirmou
        if(gerarCodigo){
            // cria nova string
            codigo = new String();
            codigo += painelSelecionaPeca1.getSelected() + ".cor(" +
                    cor.toLowerCase() + ")";
        }
        return codigo;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSelecionaPeca1 = new PainelSelecionaPeca();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jbtConfirma = new javax.swing.JButton();
        jbtCancela = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione a Cor"));

        jRadioButton1.setText("Preto");
        jRadioButton1.setName("Preto"); // NOI18N
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1corEscolhida(evt);
            }
        });

        jRadioButton2.setForeground(new java.awt.Color(128, 58, 58));
        jRadioButton2.setText("Marrom");
        jRadioButton2.setName("Marrom"); // NOI18N
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2corEscolhida(evt);
            }
        });

        jRadioButton3.setForeground(new java.awt.Color(0, 128, 0));
        jRadioButton3.setText("Verde");
        jRadioButton3.setName("Verde"); // NOI18N
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton3corEscolhida(evt);
            }
        });

        jRadioButton4.setForeground(new java.awt.Color(128, 128, 0));
        jRadioButton4.setText("Oliva");
        jRadioButton4.setName("Oliva"); // NOI18N
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton4corEscolhida(evt);
            }
        });

        jRadioButton5.setForeground(new java.awt.Color(0, 64, 128));
        jRadioButton5.setText("AzulMarinho");
        jRadioButton5.setName("AzulMarinho"); // NOI18N
        jRadioButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton5corEscolhida(evt);
            }
        });

        jRadioButton6.setForeground(new java.awt.Color(128, 0, 128));
        jRadioButton6.setText("Violeta");
        jRadioButton6.setName("Violeta"); // NOI18N
        jRadioButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton6corEscolhida(evt);
            }
        });

        jRadioButton7.setForeground(new java.awt.Color(0, 128, 128));
        jRadioButton7.setText("VerdePiscina");
        jRadioButton7.setName("VerdePiscina"); // NOI18N
        jRadioButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton7corEscolhida(evt);
            }
        });

        jRadioButton8.setForeground(new java.awt.Color(128, 128, 128));
        jRadioButton8.setText("Cinza");
        jRadioButton8.setName("Cinza"); // NOI18N
        jRadioButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton8corEscolhida(evt);
            }
        });

        jRadioButton9.setForeground(new java.awt.Color(192, 192, 192));
        jRadioButton9.setText("Prata");
        jRadioButton9.setName("Prata"); // NOI18N
        jRadioButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton9corEscolhida(evt);
            }
        });

        jRadioButton10.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButton10.setText("Vermelho");
        jRadioButton10.setName("Vermelho"); // NOI18N
        jRadioButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton10corEscolhida(evt);
            }
        });

        jRadioButton11.setForeground(new java.awt.Color(0, 255, 0));
        jRadioButton11.setText("VerdeLima");
        jRadioButton11.setName("VerdeLima"); // NOI18N
        jRadioButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton11corEscolhida(evt);
            }
        });

        jRadioButton12.setForeground(new java.awt.Color(255, 255, 0));
        jRadioButton12.setText("Amarelo");
        jRadioButton12.setName("Amarelo"); // NOI18N
        jRadioButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton12corEscolhida(evt);
            }
        });

        jRadioButton13.setForeground(new java.awt.Color(0, 0, 255));
        jRadioButton13.setText("Azul");
        jRadioButton13.setName("Azul"); // NOI18N
        jRadioButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton13corEscolhida(evt);
            }
        });

        jRadioButton14.setForeground(new java.awt.Color(255, 0, 128));
        jRadioButton14.setText("Rosa");
        jRadioButton14.setName("Rosa"); // NOI18N
        jRadioButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton14corEscolhida(evt);
            }
        });

        jRadioButton15.setForeground(new java.awt.Color(0, 255, 255));
        jRadioButton15.setText("AzulPiscina");
        jRadioButton15.setName("AzulPiscina"); // NOI18N
        jRadioButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton15corEscolhida(evt);
            }
        });

        jRadioButton16.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton16.setText("Branco");
        jRadioButton16.setName("Branco"); // NOI18N
        jRadioButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton16corEscolhida(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton14))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton15))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton16)
                    .addComponent(jRadioButton12)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jRadioButton8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton16))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButton3)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jRadioButton7)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton15))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButton2)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jRadioButton6)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton14))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jRadioButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton13))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jbtConfirma.setText("Confirmar");
        jbtConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConfirmaconfirma(evt);
            }
        });

        jbtCancela.setText("Cancelar");
        jbtCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelacancelar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelSelecionaPeca1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                        .addGap(162, 162, 162)
                        .addComponent(jbtCancela, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSelecionaPeca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtCancela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void jbtConfirmaconfirma(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConfirmaconfirma
    // Valida os Campos
    if(validaEntrada()){
        // se valiu retorna
        gerarCodigo = true;
        dialog.setVisible(false);
    }
}//GEN-LAST:event_jbtConfirmaconfirma

private void jbtCancelacancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelacancelar
    dialog.setVisible(false);
}//GEN-LAST:event_jbtCancelacancelar

private void jRadioButton1corEscolhida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1corEscolhida
        cor = evt.getComponent().getName();
}//GEN-LAST:event_jRadioButton1corEscolhida

private void jRadioButton2corEscolhida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2corEscolhida
        cor = evt.getComponent().getName();
}//GEN-LAST:event_jRadioButton2corEscolhida

private void jRadioButton3corEscolhida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3corEscolhida
        cor = evt.getComponent().getName();
}//GEN-LAST:event_jRadioButton3corEscolhida

private void jRadioButton4corEscolhida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton4corEscolhida
        cor = evt.getComponent().getName();
}//GEN-LAST:event_jRadioButton4corEscolhida

private void jRadioButton5corEscolhida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton5corEscolhida
        cor = evt.getComponent().getName();
}//GEN-LAST:event_jRadioButton5corEscolhida

private void jRadioButton6corEscolhida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton6corEscolhida
        cor = evt.getComponent().getName();
}//GEN-LAST:event_jRadioButton6corEscolhida

private void jRadioButton7corEscolhida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton7corEscolhida
        cor = evt.getComponent().getName();
}//GEN-LAST:event_jRadioButton7corEscolhida

private void jRadioButton8corEscolhida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton8corEscolhida
        cor = evt.getComponent().getName();
}//GEN-LAST:event_jRadioButton8corEscolhida

private void jRadioButton9corEscolhida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton9corEscolhida
        cor = evt.getComponent().getName();
}//GEN-LAST:event_jRadioButton9corEscolhida

private void jRadioButton10corEscolhida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton10corEscolhida
        cor = evt.getComponent().getName();
}//GEN-LAST:event_jRadioButton10corEscolhida

private void jRadioButton11corEscolhida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton11corEscolhida
        cor = evt.getComponent().getName();
}//GEN-LAST:event_jRadioButton11corEscolhida

private void jRadioButton12corEscolhida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton12corEscolhida
        cor = evt.getComponent().getName();
}//GEN-LAST:event_jRadioButton12corEscolhida

private void jRadioButton13corEscolhida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton13corEscolhida
        cor = evt.getComponent().getName();
}//GEN-LAST:event_jRadioButton13corEscolhida

private void jRadioButton14corEscolhida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton14corEscolhida
        cor = evt.getComponent().getName();
}//GEN-LAST:event_jRadioButton14corEscolhida

private void jRadioButton15corEscolhida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton15corEscolhida
        cor = evt.getComponent().getName();
}//GEN-LAST:event_jRadioButton15corEscolhida

private void jRadioButton16corEscolhida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton16corEscolhida
        cor = evt.getComponent().getName();
}//GEN-LAST:event_jRadioButton16corEscolhida


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JButton jbtCancela;
    private javax.swing.JButton jbtConfirma;
    private PainelSelecionaPeca painelSelecionaPeca1;
    // End of variables declaration//GEN-END:variables

    private boolean validaEntrada(){
        if (cor == null){
            Msg.erro("Escolha uma cor!");
            return false;
        }
        if(painelSelecionaPeca1.getSelected() == null){
            Msg.erro("Entrada inv�lida!");
            painelSelecionaPeca1.requestFocus();
            return false;
        }
        return true;
    }
}
