/*
 * ModoDinamico.java
 *
 * Created on 19 de Maio de 2008, 18:49
 */

package tangram.gui;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;

import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author  GlauKo
 */
public class ModoDinamico extends javax.swing.JPanel {
    
    JDialog dialog;
    String nomeObetoParaMover;
    ArrayList<String> acoes;
    float[] parms;
    
    float x,y,z;
    int repeticoes, tempo;
    String acaoSelecionada;
    
    boolean gerarCodigo;
    static String SELECIONE_UMA_ACAO = "Selecione uma Ação";

    public String getAcaoSelecionada() {
        return acaoSelecionada;
    }

    public void setAcaoSelecionada(String acaoSelecionada) {
        this.acaoSelecionada = acaoSelecionada;
    }
    
    /** Creates new form ModoDinamico */
    public ModoDinamico(String nomeObjetoParaMover,
            ArrayList<String> acoes,
            float[] parms) {
        this.nomeObetoParaMover = nomeObjetoParaMover;
        this.acoes = acoes;
        this.parms = parms;
        initComponents();
        gerarCodigo = false;
        jtX.setText(String.valueOf(Math.round(parms[0])));
        jtY.setText(String.valueOf(Math.round(parms[1])));
        jtZ.setText(String.valueOf(Math.round(parms[2])));
        jtRepeticoes.setText("10");
        jtTempo.setText("1000");
        jcbAcao.removeAllItems();
        jcbAcao.addItem(SELECIONE_UMA_ACAO);
        for(String s : acoes){
            jcbAcao.addItem(s);
        }
    }
    
    public String showDialog(JFrame frame){
        String codigo = null;
        if( dialog == null){
            // cria um novo dialog
            dialog = new JDialog(frame, "Modo Dinâmico", true);
            // adiciona este painel no dialog
            dialog.add(this);
            dialog.pack();
            Dimension tela =  Toolkit.getDefaultToolkit().getScreenSize();  
            dialog.setLocation( (tela.width - dialog.getSize().width)/2, 
                    (tela.height - dialog.getSize().height)/2 );
        }
        // mostra o dialog e segura a execução atÃ© o fechamento do mesmo
        dialog.setVisible(true);
        // se confirmou
        if(gerarCodigo){
            // cria nova string
            codigo = "";
            
            // concatena o comando repita
            codigo += "repita " +
                    jtRepeticoes.getText() +
                    " vezes inicio\n";
            
            // calcula os valores dos passos
            x = Math.round(x/repeticoes);
            y = Math.round(y/repeticoes);
            z = Math.round(z/repeticoes);
            
            // concatena o comando para mover
            codigo += "    " + nomeObetoParaMover +
                    ".move(" + String.valueOf(x) +
                    ", " + String.valueOf(y) +
                    ", " + String.valueOf(z) +
                    ")\n";
            
            // se seleciona acao, concatena comando faça
            if(acaoSelecionada != null && 
                    !acaoSelecionada.equals(SELECIONE_UMA_ACAO))
                codigo += "    faça " + 
                        acaoSelecionada +
                        "\n";
            
            // concatena o comando pisca
            tempo = Math.round(tempo/repeticoes);
            codigo += "    pisca(" +
                    String.valueOf(tempo) +
                    ")\n";
            
            // concatena o fim do comando repita
            codigo += "fim\n";
        }
        // retorna a cor selecionada
        return codigo;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        distancia = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtX = new javax.swing.JTextField();
        jtY = new javax.swing.JTextField();
        jtZ = new javax.swing.JTextField();
        interacoes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtRepeticoes = new javax.swing.JTextField();
        jtTempo = new javax.swing.JTextField();
        acaoAExecutar = new javax.swing.JPanel();
        jcbAcao = new javax.swing.JComboBox();
        jbtConfirma = new javax.swing.JButton();
        jbtCancela = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(249, 261));

        distancia.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores da distância a percorrer"));

        jLabel1.setText("X");

        jLabel2.setText("Y");

        jLabel3.setText("Z");

        jtX.setText("123456");

        jtY.setText("123456");

        jtZ.setText("123456");

        javax.swing.GroupLayout distanciaLayout = new javax.swing.GroupLayout(distancia);
        distancia.setLayout(distanciaLayout);
        distanciaLayout.setHorizontalGroup(
            distanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(distanciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtX, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtY, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtZ, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );
        distanciaLayout.setVerticalGroup(
            distanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(distanciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(distanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jtZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        interacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Iteração da distância a percorrer"));

        jLabel4.setText("Número de Repetições");

        jLabel5.setText("Tempo do percurso");

        jtRepeticoes.setText("123");

        jtTempo.setText("12345");

        javax.swing.GroupLayout interacoesLayout = new javax.swing.GroupLayout(interacoes);
        interacoes.setLayout(interacoesLayout);
        interacoesLayout.setHorizontalGroup(
            interacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(interacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(interacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(49, 49, 49)
                .addGroup(interacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtRepeticoes, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jtTempo, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addContainerGap())
        );
        interacoesLayout.setVerticalGroup(
            interacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(interacoesLayout.createSequentialGroup()
                .addGroup(interacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtRepeticoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(interacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        acaoAExecutar.setBorder(javax.swing.BorderFactory.createTitledBorder("Executar Ação na Iteração"));

        jcbAcao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${acaoSelecionada}"), jcbAcao, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout acaoAExecutarLayout = new javax.swing.GroupLayout(acaoAExecutar);
        acaoAExecutar.setLayout(acaoAExecutarLayout);
        acaoAExecutarLayout.setHorizontalGroup(
            acaoAExecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acaoAExecutarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbAcao, 0, 201, Short.MAX_VALUE)
                .addContainerGap())
        );
        acaoAExecutarLayout.setVerticalGroup(
            acaoAExecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcbAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jbtConfirma.setText("Confirmar");
        jbtConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirma(evt);
            }
        });

        jbtCancela.setText("Cancelar");
        jbtCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(acaoAExecutar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addGap(75, 75, 75)
                        .addComponent(jbtCancela, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                    .addComponent(interacoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(distancia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(distancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(interacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acaoAExecutar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtCancela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void confirma(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirma
        // Valida os Campos
        if(validaEntrada()){
            // se valiu retorna
            gerarCodigo = true;
            dialog.setVisible(false);
        }
}//GEN-LAST:event_confirma

    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        dialog.setVisible(false);
    }//GEN-LAST:event_cancelar
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acaoAExecutar;
    private javax.swing.JPanel distancia;
    private javax.swing.JPanel interacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtCancela;
    private javax.swing.JButton jbtConfirma;
    private javax.swing.JComboBox jcbAcao;
    private javax.swing.JTextField jtRepeticoes;
    private javax.swing.JTextField jtTempo;
    private javax.swing.JTextField jtX;
    private javax.swing.JTextField jtY;
    private javax.swing.JTextField jtZ;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private boolean validaEntrada() {
        try{
            x = Float.parseFloat(jtX.getText());
        } catch(Exception e) {
            Msg.erro("Entrada inválida!");
            jtX.requestFocus();
            return false;
        }
        try{
            y = Float.parseFloat(jtY.getText());
        } catch(Exception e) {
            Msg.erro("Entrada inválida!");
            jtY.requestFocus();
            return false;
        }
        try{
            z = Float.parseFloat(jtZ.getText());
        } catch(Exception e) {
            Msg.erro("Entrada inválida!");
            jtZ.requestFocus();
            return false;
        }
        try{
            repeticoes = Integer.parseInt(jtRepeticoes.getText());
        } catch(Exception e) {
            Msg.erro("Entrada inválida!");
            jtRepeticoes.requestFocus();
            return false;
        }
        try{
            tempo = Integer.parseInt(jtTempo.getText());
        } catch(Exception e) {
            Msg.erro("Entrada inválida!");
            jtTempo.requestFocus();
            return false;
        }
        if(repeticoes <= 0){
            Msg.erro("Entrada inválida!");
            jtRepeticoes.requestFocus();
            return false;
        }
        if (tempo <= 0){
            Msg.erro("Entrada inválida!");
            jtTempo.requestFocus();
            return false;
        }
        return true;
    }
    
}
