/*
 * PainelSelecionaPeca.java
 *
 * Created on 5 de Julho de 2008, 15:50
 */

package tangram.gui;

import java.util.ArrayList;

/**
 *
 * @author  GlauKo
 */
public class PainelSelecionaPeca extends javax.swing.JPanel {

    ArrayList<String> listaParaSelecao;
    
    /** Creates new form PainelSelecionaPeca */
    public PainelSelecionaPeca() {
        initComponents();
    }

    public void setListaParaSelecao(ArrayList<String> listaParaSelecao) {
        this.listaParaSelecao = listaParaSelecao;
        jcbSelecao.removeAllItems();
        for (String s : listaParaSelecao){
            jcbSelecao.addItem(s);
        }
    }

    public ArrayList<String> getListaParaSelecao() {
        return listaParaSelecao;
    }
    
    public String getSelected(){
        return (String) jcbSelecao.getSelectedItem();
    }
    
    @Override
    public void requestFocus(){
        jcbSelecao.requestFocus();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbSelecao = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione a Peça ou Modelo"));

        jLabel1.setText("Selecione");

        jcbSelecao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox jcbSelecao;
    // End of variables declaration//GEN-END:variables

}
