/*
 * AbrirArquivo.java
 *
 * Created on 4 de Abril de 2008, 00:56
 */

package tangram.io;

import java.io.File;

import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author  GlauKo
 */
public class AbrirArquivo extends javax.swing.JPanel {
    
    private JDialog dialog;
    private File selectFile;
    
    /** Creates new form AbrirArquivo */
    public AbrirArquivo(boolean mod, boolean mun) {
        initComponents();
        
        jFileChooser1.setMultiSelectionEnabled(false);
        jFileChooser1.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        javax.swing.filechooser.FileFilter ff1 = new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File f) {
                if(f.isDirectory()){
                    return true;
                }
                else{
                    return f.getName().toLowerCase().endsWith(".mun");
                }
            }
            @Override
            public String getDescription() {
                return "Mundo";
            }
        };
        if(mun)
            jFileChooser1.addChoosableFileFilter(ff1);
        
        javax.swing.filechooser.FileFilter ff2 = new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File f) {
                if(f.isDirectory()){
                    return true;
                }
                else{
                    return f.getName().toLowerCase().endsWith(".mod");
                }
            }
            @Override
            public String getDescription() {
                return "Modelo";
            }
        };
        if(mod)
            jFileChooser1.addChoosableFileFilter(ff2);
    }
    
    public File showDialog(JFrame frame){
        // Se ainda Não existe o Dialog
        if(dialog == null){
            // cria um novo dialog
            dialog = new JDialog(frame, "Abrir Arquivo", true);
            // adiciona este painel no dialog
            dialog.add(this);
            dialog.pack();
        }
        // mostra o dialog e segura a execução até o fechamento do mesmo
        dialog.setVisible(true);
        // se selecionou algum arquivo 
        if(selectFile != null){
            String appPath = System.getProperties().getProperty("user.dir");
            if(!selectFile.getParent().equals(appPath)){
                File newFile = new File(appPath + "\\" + selectFile.getName());
                if(selectFile.renameTo(newFile))
                    selectFile = newFile;
            }
        }
        // retorna o arquivo selecionado
        return selectFile;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        jFileChooser1.setCurrentDirectory(new File(new File(".").getAbsolutePath()));
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        selectFile = jFileChooser1.getSelectedFile();
        dialog.setVisible(false);
    }//GEN-LAST:event_jFileChooser1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
    
}
