package gals;

public interface ParserConstants
{
    String[] PARSER_ERROR =
    {
        "",
        "Era esperado o fim do programa!",
        "Era esperado um identificador!",
        "Era esperado um numero!",
        "Era esperado modelo!",
        "Era esperado metodo!",
        "Era esperado mundo!",
        "Era esperado CRIA!",
        "Era esperado VIVA!",
        "Era esperado APAGA!",
        "Era esperado TERMINA!",
        "Era esperado gira!",
        "Era esperado cor!",
        "Era esperado espelha!",
        "Era esperado repita!",
        "Era esperado em!",
        "Era esperado paralelo!",
        "Era esperado faca!",
        "Era esperado depois!",
        "Era esperado de!",
        "Era esperado no!",
        "Era esperado ponto!",
        "Era esperado inicio!",
        "Era esperado fim!",
        "Era esperado cria!",
        "Era esperado como!",
        "Era esperado move!",
        "Era esperado pisca!",
        "Era esperado vezes!",
        "Era esperado p1!",
        "Era esperado p2!",
        "Era esperado p3!",
        "Era esperado p4!",
        "Era esperado p5!",
        "Era esperado p6!",
        "Era esperado p7!",
        "Era esperado amarelo!",
        "Era esperado azul!",
        "Era esperado azulMarinho!",
        "Era esperado azulPiscina!",
        "Era esperado branco!",
        "Era esperado cinza!",
        "Era esperado marrom!",
        "Era esperado oliva!",
        "Era esperado prata!",
        "Era esperado preto!",
        "Era esperado rosa!",
        "Era esperado verde!",
        "Era esperado verdePiscina!",
        "Era esperado verdeLima!",
        "Era esperado vermelho!",
        "Era esperado violeta!",
        "Era esperado \";\"!",
        "Era esperado \"(\"!",
        "Era esperado \")\"!",
        "Era esperado \",\"!",
        "Era esperado \".\"!",
        "Erro na escrita!",
        "Erro na escrita!",
        "Erro na escrita!",
        "Erro na escrita!",
        "Erro na escrita!",
        "Erro na escrita!",
        "Erro na escrita!",
        "Erro na escrita!",
        "Erro na escrita!",
        "Erro na escrita!",
        "Nome da Ação inválida!",
        "Erro na escrita. Comando inválido!",
        "Erro na escrita. Comando CRIA inválido!",
        "Erro na escrita. Comando inválido!",
        "Erro na escrita. Comando inválido!",
        "Erro na escrita. Comando move inválido!",
        "Erro na escrita. Comando gira inválido!",
        "Erro na escrita. Comando pisca inválido!",
        "Erro na escrita. Comando cor inválido!",
        "Erro na escrita. Comando espelha inválido!",
        "Erro na escrita. Comando repete inválido!",
        "Erro na escrita. Comando repete inválido!",
        "Erro na escrita. Comando faça inválido!",
        "Erro na escrita. em paralelo inválido!",
        "Erro na escrita!",
        "Erro na escrita. Comando CRIA inválido!",
        "Erro na escrita. Peça inválida!",
        "Erro na escrita!",
        "Erro na escrita. Cor inválida!",
        "Erro na escrita. Identificador inválido!",
        "Erro na escrita. X inválido!",
        "Erro na escrita. Y inválido!",
        "Erro na escrita. Z inválido!",
        "Erro na escrita. Comando gira inválido!",
        "Nome do mundo inválido!",
        "Erro na escrita!",
        "Erro na escrita!",
        "Erro na escrita!",
        "Erro na escrita. Comando CRIA COMO inválido!",
        "Erro na escrita. identificado do modelo inválido!",
        "Erro na escrita. Comando faça inválido!",
        "Erro na escrita. Metodo do modelo inválido!",
        "Erro na escrita. Comando VIVA inválido!"
    };
}
