/*
 * EscolheCor.java
 *
 * Created on 21 de Março de 2008, 18:24
 */

package tangram.gui;

import java.awt.Dimension;
import java.awt.Toolkit;

import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author  GlauKo
 */
public class EscolheCor extends javax.swing.JPanel {
    
    String cor, titulo;
    JDialog dialog;
    
    /** Creates new form EscolheCor */
    public EscolheCor(String cor,String titulo) {
        initComponents();
        this.titulo = titulo;
        this.cor = cor;
        if(cor.length() > 0){
            for( java.awt.Component c : getComponents()){
                if(c.getName().equals(cor)){
                    javax.swing.JRadioButton aux = (javax.swing.JRadioButton)c;
                    aux.setSelected(true);
                }
            }
        }
    }
    
    /**
     * Cria um JDialog com o Owner sendo o parametro frame e modal igual a true.
     * adciona o este JPanel no JDialog.
     * Dispara o Método show do JDialog.
     * Retorna a Cor selecionada.
     * 
     * @param frame é usado como Frame Owner do JDialog
     * @return retorna a cor escolhida
     */
    public String showDialog(JFrame frame){
        // Se ainda Não existe o Dialog
        if(dialog == null){
            // cria um novo dialog
            dialog = new JDialog(frame, titulo, true);
            // adiciona este painel no dialog
            dialog.add(this);
            dialog.pack();
            Dimension tela =  Toolkit.getDefaultToolkit().getScreenSize();  
            dialog.setLocation( (tela.width - dialog.getSize().width)/2, 
                    (tela.height - dialog.getSize().height)/2 );
        }
        // mostra o dialog e segura a execução até o fechamento do mesmo
        dialog.show();
        // retorna a cor selecionada
        return cor;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoDeCores = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();

        GrupoDeCores.add(jRadioButton1);
        jRadioButton1.setText("Preto");
        jRadioButton1.setName("Preto"); // NOI18N
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corEscolhida(evt);
            }
        });

        GrupoDeCores.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(128, 58, 58));
        jRadioButton2.setText("Marrom");
        jRadioButton2.setName("Marrom"); // NOI18N
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corEscolhida(evt);
            }
        });

        GrupoDeCores.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(0, 128, 0));
        jRadioButton3.setText("Verde");
        jRadioButton3.setName("Verde"); // NOI18N
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corEscolhida(evt);
            }
        });

        GrupoDeCores.add(jRadioButton4);
        jRadioButton4.setForeground(new java.awt.Color(128, 128, 0));
        jRadioButton4.setText("Oliva");
        jRadioButton4.setName("Oliva"); // NOI18N
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corEscolhida(evt);
            }
        });

        GrupoDeCores.add(jRadioButton5);
        jRadioButton5.setForeground(new java.awt.Color(0, 64, 128));
        jRadioButton5.setText("AzulMarinho");
        jRadioButton5.setName("AzulMarinho"); // NOI18N
        jRadioButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corEscolhida(evt);
            }
        });

        GrupoDeCores.add(jRadioButton6);
        jRadioButton6.setForeground(new java.awt.Color(128, 0, 128));
        jRadioButton6.setText("Violeta");
        jRadioButton6.setName("Violeta"); // NOI18N
        jRadioButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corEscolhida(evt);
            }
        });

        GrupoDeCores.add(jRadioButton7);
        jRadioButton7.setForeground(new java.awt.Color(0, 128, 128));
        jRadioButton7.setText("VerdePiscina");
        jRadioButton7.setName("VerdePiscina"); // NOI18N
        jRadioButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corEscolhida(evt);
            }
        });

        GrupoDeCores.add(jRadioButton8);
        jRadioButton8.setForeground(new java.awt.Color(128, 128, 128));
        jRadioButton8.setText("Cinza");
        jRadioButton8.setName("Cinza"); // NOI18N
        jRadioButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corEscolhida(evt);
            }
        });

        GrupoDeCores.add(jRadioButton9);
        jRadioButton9.setForeground(new java.awt.Color(192, 192, 192));
        jRadioButton9.setText("Prata");
        jRadioButton9.setName("Prata"); // NOI18N
        jRadioButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corEscolhida(evt);
            }
        });

        GrupoDeCores.add(jRadioButton10);
        jRadioButton10.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButton10.setText("Vermelho");
        jRadioButton10.setName("Vermelho"); // NOI18N
        jRadioButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corEscolhida(evt);
            }
        });

        GrupoDeCores.add(jRadioButton11);
        jRadioButton11.setForeground(new java.awt.Color(0, 255, 0));
        jRadioButton11.setText("VerdeLima");
        jRadioButton11.setName("VerdeLima"); // NOI18N
        jRadioButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corEscolhida(evt);
            }
        });

        GrupoDeCores.add(jRadioButton12);
        jRadioButton12.setForeground(new java.awt.Color(255, 255, 0));
        jRadioButton12.setText("Amarelo");
        jRadioButton12.setName("Amarelo"); // NOI18N
        jRadioButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corEscolhida(evt);
            }
        });

        GrupoDeCores.add(jRadioButton13);
        jRadioButton13.setForeground(new java.awt.Color(0, 0, 255));
        jRadioButton13.setText("Azul");
        jRadioButton13.setName("Azul"); // NOI18N
        jRadioButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corEscolhida(evt);
            }
        });

        GrupoDeCores.add(jRadioButton14);
        jRadioButton14.setForeground(new java.awt.Color(255, 0, 128));
        jRadioButton14.setText("Rosa");
        jRadioButton14.setName("Rosa"); // NOI18N
        jRadioButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corEscolhida(evt);
            }
        });

        GrupoDeCores.add(jRadioButton15);
        jRadioButton15.setForeground(new java.awt.Color(0, 255, 255));
        jRadioButton15.setText("AzulPiscina");
        jRadioButton15.setName("AzulPiscina"); // NOI18N
        jRadioButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corEscolhida(evt);
            }
        });

        GrupoDeCores.add(jRadioButton16);
        jRadioButton16.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton16.setText("Branco");
        jRadioButton16.setName("Branco"); // NOI18N
        jRadioButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corEscolhida(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton16)
                    .addComponent(jRadioButton12)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jRadioButton8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton16))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButton3)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jRadioButton7)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton15))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButton2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jRadioButton6)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton14))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRadioButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton13))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento disparado ao clicar em um JRadioButton. A cor seleciona passa a
     * ser a String do atributo name do Component que criou este evento.
     * Após a execução, chama o método hide do JDialog em que este JPanel se encontra.
     * 
     * @param evt evento disparado por um Component
     */
    private void corEscolhida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_corEscolhida
        cor = evt.getComponent().getName();
        if (dialog != null)
            dialog.hide();
    }//GEN-LAST:event_corEscolhida
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoDeCores;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables
    
}
