package gals;

public interface ParserConstants
{
    String[] PARSER_ERROR =
    {
        "",
        "Era esperado fim de programa",
        "Era esperado identificador",
        "Era esperado jsml",
        "Era esperado numero",
        "Era esperado sobreposto",
        "Era esperado modelo",
        "Era esperado metodo",
        "Era esperado mundo",
        "Era esperado CRIA",
        "Era esperado VIVA",
        "Era esperado APAGA",
        "Era esperado TERMINA",
        "Era esperado gira",
        "Era esperado cor",
        "Era esperado espelha",
        "Era esperado repita",
        "Era esperado em",
        "Era esperado paralelo",
        "Era esperado faca",
        "Era esperado depois",
        "Era esperado de",
        "Era esperado no",
        "Era esperado ponto",
        "Era esperado inicio",
        "Era esperado fim",
        "Era esperado cria",
        "Era esperado como",
        "Era esperado move",
        "Era esperado piscar",
        "Era esperado vezes",
        "Era esperado Peca1",
        "Era esperado Peca2",
        "Era esperado Peca3",
        "Era esperado Peca4",
        "Era esperado Peca5",
        "Era esperado Peca6",
        "Era esperado Peca7",
        "Era esperado amarelo",
        "Era esperado azul",
        "Era esperado azulMarinho",
        "Era esperado azulPiscina",
        "Era esperado branco",
        "Era esperado cinza",
        "Era esperado marrom",
        "Era esperado oliva",
        "Era esperado prata",
        "Era esperado preto",
        "Era esperado rosa",
        "Era esperado verde",
        "Era esperado verdePiscina",
        "Era esperado verdeLima",
        "Era esperado vermelho",
        "Era esperado violeta",
        "Era esperado fala",
        "Era esperado enquanto",
        "Era esperado espera",
        "Era esperado \";\"",
        "Era esperado \"(\"",
        "Era esperado \")\"",
        "Era esperado \",\"",
        "Era esperado \".\"",
        "<codigo> inválido",
        "<modelo> inválido",
        "<Lista_de_metodos> inválido",
        "<metodos_outros> inválido",
        "<metodo_cria> inválido",
        "<metodo> inválido",
        "<bloco> inválido",
        "<bloco_2> inválido",
        "<comando> inválido",
        "<comandos_em_ids> inválido",
        "<comando_de_id> inválido",
        "<comando_cria> inválido",
        "<cria_extra> inválido",
        "<extra> inválido",
        "<id> inválido",
        "<comando_move> inválido",
        "<comando_gira> inválido",
        "<gira_extra> inválido",
        "<comando_cor> inválido",
        "<comando_espelha> inválido",
        "<comando_piscar> inválido",
        "<comando_repete> inválido",
        "<comando_faca> inválido",
        "<figura> inválido",
        "<nome_Metodo> inválido",
        "<modelo_id> inválido",
        "<nome_do_mundo> inválido",
        "<peca> inválido",
        "<cor> inválido",
        "<X> inválido",
        "<Y> inválido",
        "<Z> inválido",
        "<mundo> inválido",
        "<bloco_do_mundo> inválido",
        "<bloco_do_mundo_2> inválido",
        "<comando_mundo> inválido",
        "<comando_cria_como> inválido",
        "<comando_repete_mundo> inválido",
        "<comando_faca_mundo> inválido",
        "<metodo_do_id> inválido",
        "<comando_viva> inválido",
        "<em_paralelo> inválido",
        "<comando_fala> inválido",
        "<comando_fala_sobreposto> inválido",
        "<comando_enquanto_fala> inválido",
        "<comando_espera_fala> inválido"
    };
}
